### ISSUE TITLE
Question: Can I only tweets from 2023 and older?

### ISSUE THREAD

**Issue by TwisterMc** [lucahammer/tweetXer#18]
I'd like to just delete old tweets. Is that possible? Or is this an all or none solution?

**Comment by lucahammer** [comment]
TweetXer is meant as an all or nothing solution allowing people to move on from X Corp. Because of that I won't add things that help people to stay.

You can edit your tweet-headers.js or tweets.js file, whatever you use for deleting Tweets, and remove the Tweets you want to keep. If they aren't in the file and you only use that file, TweetXer won't be able to delete anything else.

https://bsky.app/profile/luca.run/post/3lavia6ltlc2g
