### ISSUE TITLE
Chromium based browsers stuck after 10k

### ISSUE THREAD

**Issue by lucahammer** [lucahammer/tweetXer#2]
For some reason Chromium based browsers (Chrome, Microsoft Edge, Brave,...) stall after the deletion of 10k Tweets. By using the Advanced Options and skipping the already removed Tweets, the rest of the Tweets can be deleted.

Firefox does not have this issue and removes up to 350k Tweets in one go. Probably more, but that was the highest amount that got reported back.

**Comment by lucahammer** [comment]
Closing the browser console after pasting the script seems to improve speed and memory usage. I wasn't able to reproduce the issue myself, but maybe someone who experiences it, could test if closing the browser console solves it.

**Comment by STrRedWolf** [comment]
Looking at the script myself in Chrome, as I'm hitting timeouts after ~900 tweets.  I've made a modification to deleteTweets() that adds a 5 second timeout (given that the replies come back in under 100 milliseconds).  If it times out, it warns the user, pushes the tweet ID back in, and sleeps for 15 seconds.  It then loops back around.

I also added some style tweaks because I'm using dark mode and it's inheriting the white text.

[tweetxer-0.6.6-rw.userscript.txt](https://github.com/user-attachments/files/17777427/tweetxer-0.6.6-rw.userscript.txt)

**Comment by lucahammer** [comment]
That sounds great, do you want to create a pull request or should I add the modifications directly?

**Comment by STrRedWolf** [comment]
Apologies for not getting on this earlier.  It's been a busy few days. :(

**Comment by lucahammer** [comment]
Thanks for getting involved anyways. As you may have seen, I added your suggestions and added you as an author.
