### ISSUE TITLE
XHR interception fails in userscript

### ISSUE THREAD

**Issue by KingdomFantasy6** [lucahammer/tweetXer#24]
Browser: Firefox (latest update I think)
Computer: Windows 10, 8gb ram
Additional Plugins?: Disabled ublock+, ghostery, and duck duck go (i know, overkill), when I noticed things weren't quite working. All twitter related plugins have been disabled. I used tampermonkey to help with the script.

I tried tweet-header.js as well as tweets.js but both seem to be having the same issues of not deleting tweets. I'll select, get the progress bar and "deleting 24, 756 tweets", theeeeeen nada. Tried without, didn't see anything happening, then on refresh noticed the console said there were zero tweets, but there were still tweets.

The main consistencies during all this is the console will provide errors about object-src violating the directive "object-src none". "scrpt-src" also seems to have been deemed "unsafe". Then there'll be over a hundred network errors.

Here's a few screenshots that'll hopefully make some sense to you!
![image](https://github.com/user-attachments/assets/a181e7b3-f771-4afb-abc7-68de908fa0bc)

![image](https://github.com/user-attachments/assets/fefc4b58-dd1d-42bb-9fec-8b4d7ceb1857)

![image](https://github.com/user-attachments/assets/60068678-48f1-4d5c-9a86-bad3d191d6a9)

![image](https://github.com/user-attachments/assets/a8afa788-79fb-4b2c-9e8e-0ff8a8bada84)

Okay now the debugger is just messing with me. It worked before, only for me to realize I couldn't edit anything, not sure why it's being weird now.

![image](https://github.com/user-attachments/assets/f6c4b18a-3562-44c9-8c6b-be251a3069e4)

Anyways, hopes this info helps with any debugging, best of luck, especially given how much of a workout this script is getting!

**Comment by KingdomFantasy6** [comment]
Update: After poking through some closed issues, I copy pasted into the console. That method worked, so I'm uncertain if its an issue with tampermonkey or what.

Anyways, thanks again for creating this! That would have been a LOT of tweets to manually delete...

**Comment by satmandu** [comment]
@KingdomFantasy6 Thanks for that info! Pasting into the console does allow this to work! the various js loading monkey plugins were causing the problem, it seems!

**Comment by lucahammer** [comment]
After some testing, it seems that the userscript only works in Chrome. Tested with tampermonkey. Which is funny because the script pasted to the console works best with Firefox.

For some reason, probably security, the script can't intercept XHR requests in Firefox when run as an userscript. 
If someone has an idea how to fix it, these these lines are the issue:
https://github.com/lucahammer/tweetXer/blob/e05a130717dbd1341d801b728a516f9e97efa56e/tweetXer.js#L54

Deletion doesn't start because it waits for a header with authorization: https://github.com/lucahammer/tweetXer/blob/e05a130717dbd1341d801b728a516f9e97efa56e/tweetXer.js#L356

**Comment by lucahammer** [comment]
I removed the interception and use cookies instead. I hope this won't result in other issues.
