### ISSUE TITLE
Feature request: delete direct messages

### ISSUE THREAD

**Issue by jeremiahlee** [lucahammer/tweetXer#3]
I would love the ability to also delete all of my direct messages.

**Comment by theit** [comment]
Yes, that would be very cool.

**Comment by eGit** [comment]
Just dick pics.

**Comment by lucahammer** [comment]
I found two options for deleting DMs.

Deleting individual messages by sending requests to "/i/api/graphql/BJ6DtxA2llfjnRoRjaiIiw/DMMessageDeleteMutation" with {"variables":{"messageId":"XXX","requestId":"XX-XX-XX-XX-XX"},"queryId":"XXXX"}

Deleting whole conversations:
/i/api/1.1/dm/conversation/XXX-XXX/delete.json

In both cases X Corp says, that the messages are still available to other participants of the conversation.
![image](https://github.com/user-attachments/assets/9f5ab167-0092-4460-b2ad-3b3486c24bef)
![image](https://github.com/user-attachments/assets/af383271-3734-43fa-9a39-bafeeaf8e284)

Neither of those sound useful.

**Comment by lucahammer** [comment]
Added with version 0.9. Because of rate limits I went with "Leave conversation" as default. To delete messages individually, you have to edit the script in Line 36: "deleteDMsOneByOne: true,".

According to former engineers messages are removed from the server, when all participants delete them: https://bsky.app/profile/triketora.com/post/3lcbmqzo4uk25
